In [37]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [38]:


df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [39]:
df.head()

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000

In [40]:
df['age']=df['age'].fillna(df['age'].median())
df['city']=df['city'].fillna(df['city'].mode()[0])
df.head()

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000

##Encoding
#one hot encoding to city label encoding to grnder

In [41]:
df['city'].value_counts()

city
Delhi     4
Mumbai    2
Name: count, dtype: int64

In [42]:
df = pd.get_dummies(df, columns=['city'], drop_first=False)
df.head(10)

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0    Male          40000       False         True
1            2  35.0  Female          80000        True        False
2            3  35.0  Female          60000        True        False
3            4  35.0    Male         120000       False         True
4            2  35.0  Female          80000        True        False
5            5  40.0    Male          95000        True        False

In [43]:
df['gender'].value_counts()

gender
Male      3
Female    3
Name: count, dtype: int64

In [44]:
df['gender']=df['gender'].map({'Male':0,'Female':1})
df.head(10)

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       0          40000       False         True
1            2  35.0       1          80000        True        False
2            3  35.0       1          60000        True        False
3            4  35.0       0         120000       False         True
4            2  35.0       1          80000        True        False
5            5  40.0       0          95000        True        False

PRinting the resulting DF

In [45]:
df.head()

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       0          40000       False         True
1            2  35.0       1          80000        True        False
2            3  35.0       1          60000        True        False
3            4  35.0       0         120000       False         True
4            2  35.0       1          80000        True        False

#scaling

In [46]:

# Copy dataframe for scaling
df_minmax = df.copy()
df_standard = df.copy()

# Columns to scale
cols = ['age', 'annual_income']

# Min-Max Scaling
minmax = MinMaxScaler()
df_minmax[cols] = minmax.fit_transform(df_minmax[cols])

print("\nMin-Max Scaled Data:")
print(df_minmax)

# Standardization
scaler = StandardScaler()
df_standard[cols] = scaler.fit_transform(df_standard[cols])

print("\nStandardized Data:")
print(df_standard)

Min-Max Scaled Data:
   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       0         0.0000       False         True
1            2  0.666667       1         0.5000        True        False
2            3  0.666667       1         0.2500        True        False
3            4  0.666667       0         1.0000       False         True
4            2  0.666667       1         0.5000        True        False
5            5  1.000000       0         0.6875        True        False

Standardized Data:
   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -2.042649       0      -1.552077       False         True
1            2  0.185695       1       0.033023        True        False
2            3  0.185695       1      -0.759527        True        False
3            4  0.185695       0       1.618123       False         True
4            2  0.185695       1       0.033023        True        False
5            5  1.299867       0       0.627435        True        False